import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, useColorScheme } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { getColors } from '@/styles/commonStyles';
import { useUserRole } from '@/hooks/useUserRole';
import { fetchOwnerTrainingTemplates, fetchOwnerTrainingTemplatesContext, TrainingTemplateSummary } from '@/services/trainingTemplateService';
import { fetchOwnerPlayerCrmList, OwnerPlayerCrmPlayer, OwnerPlayerCrmTeam } from '@/services/ownerPlayerCrmService';
import { archiveTrainingProgram, enrollTrainingProgram, fetchMyTrainingPrograms, fetchTrainingPrograms, PlayerProgramEnrollment, ProgramEnrollmentStatus, publishTrainingProgram, saveTrainingProgram, setProgramEnrollmentStatus, TrainingProgram, TrainingProgramsPayload } from '@/services/trainingProgramService';

type PhaseDraft = { id: string; title: string; weekOffset: string; durationWeeks: string };
type ItemDraft = { id: string; phaseId: string; itemType: string; trainingTemplateId?: string; title: string; dayOffset: string };
type ProgramDraft = { programId?: string; title: string; description: string; audience: string; level: string; durationWeeks: string; phases: PhaseDraft[]; items: ItemDraft[] };
type BuilderStep = 1 | 2 | 3 | 4;

export const PROGRAM_LEVELS = [
  { value: 'all', label: 'All levels' },
  { value: 'beginner', label: 'Beginner' },
  { value: 'intermediate', label: 'Intermediate' },
  { value: 'advanced', label: 'Advanced' },
  { value: 'elite', label: 'Elite' },
] as const;
const normalizeProgramLevel = (value: string | null) => PROGRAM_LEVELS.some((option) => option.value === value) ? value! : 'all';

export function createProgramDraftId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (character) => {
    const random = Math.floor(Math.random() * 16);
    return (character === 'x' ? random : (random & 0x3) | 0x8).toString(16);
  });
}
const emptyDraft = (): ProgramDraft => ({ title: '', description: '', audience: '', level: 'all', durationWeeks: '4', phases: [], items: [] });
const fromProgram = (program: TrainingProgram): ProgramDraft => ({ programId: program.id, title: program.title, description: program.description ?? '', audience: program.audience ?? '', level: normalizeProgramLevel(program.level), durationWeeks: String(program.duration_weeks), phases: program.phases.map((phase) => ({ id: phase.id, title: phase.title, weekOffset: String(phase.week_offset), durationWeeks: String(phase.duration_weeks) })), items: program.items.map((item) => ({ id: item.id, phaseId: item.phase_id ?? '', itemType: item.item_type, trainingTemplateId: item.training_template_id ?? undefined, title: item.title, dayOffset: String(item.day_offset) })) });
const templateItemType = (template: TrainingTemplateSummary) => `${template.templateType}_template`;
const addDays = (start: string, offset: number) => { const date = new Date(`${start}T12:00:00`); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); };

export default function ProgramsScreen() {
  const colors = getColors(useColorScheme()); const insets = useSafeAreaInsets(); const { userRole } = useUserRole(); const isCoach = userRole === 'admin' || userRole === 'trainer';
  const [payload, setPayload] = useState<TrainingProgramsPayload | null>(null); const [mine, setMine] = useState<PlayerProgramEnrollment[]>([]); const [templates, setTemplates] = useState<TrainingTemplateSummary[]>([]);
  const [players, setPlayers] = useState<OwnerPlayerCrmPlayer[]>([]); const [teams, setTeams] = useState<OwnerPlayerCrmTeam[]>([]); const [ownerId, setOwnerId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [builderOpen, setBuilderOpen] = useState(false); const [builderStep, setBuilderStep] = useState<BuilderStep>(1); const [draft, setDraft] = useState<ProgramDraft>(emptyDraft);
  const [enrollProgram, setEnrollProgram] = useState<TrainingProgram | null>(null); const [selectedPlayers, setSelectedPlayers] = useState<string[]>([]); const [selectedTeam, setSelectedTeam] = useState<string | null>(null); const [startDate, setStartDate] = useState(new Date().toISOString().slice(0, 10));

  const load = useCallback(async () => { setError(null); try {
    if (!isCoach) { setMine((await fetchMyTrainingPrograms()).enrollments); return; }
    const context = await fetchOwnerTrainingTemplatesContext(); const nextOwner = ownerId ?? context.defaultOwnerAccountId ?? context.workspaces[0]?.ownerAccountId ?? null; setOwnerId(nextOwner); if (!nextOwner) return;
    const [programData, templateData, crm] = await Promise.all([fetchTrainingPrograms(nextOwner), fetchOwnerTrainingTemplates(nextOwner), fetchOwnerPlayerCrmList(nextOwner)]);
    setPayload(programData); setTemplates(templateData.templates.filter((template) => template.status === 'active')); setPlayers(crm.players.filter((player) => player.ownerRosterStatus === 'active')); setTeams(crm.teams);
  } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load programs.'); } finally { setLoading(false); setRefreshing(false); } }, [isCoach, ownerId]);
  useEffect(() => { void load(); }, [load]);

  const openBuilder = (program?: TrainingProgram) => { setDraft(program ? fromProgram(program) : emptyDraft()); setBuilderStep(1); setBuilderOpen(true); };
  const updateDraft = (patch: Partial<ProgramDraft>) => setDraft((current) => ({ ...current, ...patch }));
  const addPhase = () => { const offset = draft.phases.reduce((max, phase) => Math.max(max, Number(phase.weekOffset) + Number(phase.durationWeeks)), 0); updateDraft({ phases: [...draft.phases, { id: createProgramDraftId(), title: `Phase ${draft.phases.length + 1}`, weekOffset: String(offset), durationWeeks: '1' }] }); };
  const updatePhase = (id: string, patch: Partial<PhaseDraft>) => updateDraft({ phases: draft.phases.map((phase) => phase.id === id ? { ...phase, ...patch } : phase) });
  const removePhase = (id: string) => updateDraft({ phases: draft.phases.filter((phase) => phase.id !== id), items: draft.items.filter((item) => item.phaseId !== id) });
  const addTemplate = (template: TrainingTemplateSummary) => { const phaseId = draft.phases[0]?.id ?? ''; const phase = draft.phases.find((candidate) => candidate.id === phaseId); updateDraft({ items: [...draft.items, { id: createProgramDraftId(), phaseId, itemType: templateItemType(template), trainingTemplateId: template.id, title: template.title, dayOffset: String(Number(phase?.weekOffset ?? 0) * 7) }] }); };
  const addCustomItem = () => updateDraft({ items: [...draft.items, { id: createProgramDraftId(), phaseId: draft.phases[0]?.id ?? '', itemType: 'focus', title: 'New focus', dayOffset: '0' }] });
  const updateItem = (id: string, patch: Partial<ItemDraft>) => updateDraft({ items: draft.items.map((item) => item.id === id ? { ...item, ...patch } : item) });
  const removeItem = (id: string) => updateDraft({ items: draft.items.filter((item) => item.id !== id) });
  const validation = useMemo(() => { if (!draft.title.trim()) return 'Add a title.'; const duration = Number(draft.durationWeeks); if (!Number.isInteger(duration) || duration < 1 || duration > 52) return 'Duration must be 1–52 weeks.'; if (!draft.phases.length) return 'Add at least one phase.'; if (draft.phases.some((phase) => !phase.title.trim() || !Number.isInteger(Number(phase.weekOffset)) || !Number.isInteger(Number(phase.durationWeeks)) || Number(phase.weekOffset) < 0 || Number(phase.durationWeeks) < 1 || Number(phase.weekOffset) + Number(phase.durationWeeks) > duration)) return 'Check that every phase fits inside the program duration.'; if (!draft.items.length) return 'Add at least one template or focus item.'; if (draft.items.some((item) => !item.phaseId || !item.title.trim() || !Number.isInteger(Number(item.dayOffset)) || Number(item.dayOffset) < 0 || Number(item.dayOffset) >= duration * 7)) return 'Check item phases, titles and day offsets.'; return null; }, [draft]);
  const saveDraft = async () => { if (!ownerId || validation) { if (validation) Alert.alert('Program is not ready', validation); return; } setBusy(true); try { setPayload(await saveTrainingProgram({ ownerAccountId: ownerId, programId: draft.programId, title: draft.title.trim(), description: draft.description, audience: draft.audience, level: draft.level, durationWeeks: Number(draft.durationWeeks), phases: draft.phases.map((phase) => ({ id: phase.id, title: phase.title, weekOffset: Number(phase.weekOffset), durationWeeks: Number(phase.durationWeeks) })), items: draft.items.map((item) => ({ phaseId: item.phaseId || undefined, itemType: item.itemType, trainingTemplateId: item.trainingTemplateId, title: item.title, dayOffset: Number(item.dayOffset) })) })); setBuilderOpen(false); } catch (cause) { Alert.alert('Could not save program', cause instanceof Error ? cause.message : 'Try again.'); } finally { setBusy(false); } };
  const confirmPublish = (program: TrainingProgram) => Alert.alert('Publish program?', 'Publishing creates an immutable version for future enrollments.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Publish', onPress: async () => { if (!ownerId) return; setBusy(true); try { setPayload(await publishTrainingProgram(ownerId, program.id)); } catch (cause) { Alert.alert('Could not publish', cause instanceof Error ? cause.message : 'Try again.'); } finally { setBusy(false); } } }]);
  const confirmArchive = (program: TrainingProgram) => Alert.alert('Archive program?', 'Existing player history is preserved.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: async () => { if (ownerId) setPayload(await archiveTrainingProgram(ownerId, program.id)); } }]);
  const openEnrollment = (program: TrainingProgram) => { setEnrollProgram(program); setSelectedPlayers([]); setSelectedTeam(null); setStartDate(new Date().toISOString().slice(0, 10)); };
  const submitEnrollment = async () => { if (!ownerId || !enrollProgram || (!selectedPlayers.length && !selectedTeam)) return; setBusy(true); try { setPayload(await enrollTrainingProgram({ ownerAccountId: ownerId, programId: enrollProgram.id, playerIds: selectedTeam ? undefined : selectedPlayers, teamId: selectedTeam ?? undefined, startDate })); setEnrollProgram(null); } catch (cause) { Alert.alert('Could not enroll', cause instanceof Error ? cause.message : 'Try again.'); } finally { setBusy(false); } };
  const changeEnrollment = async (id: string, status: ProgramEnrollmentStatus) => { if (!ownerId) return; setBusy(true); try { setPayload(await setProgramEnrollmentStatus(ownerId, id, status)); } catch (cause) { Alert.alert('Could not update enrollment', cause instanceof Error ? cause.message : 'Try again.'); } finally { setBusy(false); } };

  if (loading && !payload && !mine.length) return <View style={[styles.center, { backgroundColor: colors.background }]}><ActivityIndicator /></View>;
  return <>
    <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18 }]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />}>
      <View style={styles.row}><View style={styles.grow}><Text style={[styles.heading, { color: colors.text }]}>{isCoach ? 'Training programs' : 'My program'}</Text><Text style={{ color: colors.textSecondary }}>{isCoach ? 'Build, publish and enroll structured player journeys.' : 'Your weeks, upcoming work and progression.'}</Text></View>{isCoach ? <TouchableOpacity testID="programs.create" style={styles.primaryCompact} onPress={() => openBuilder()}><Text style={styles.primaryText}>New</Text></TouchableOpacity> : null}</View>
      {error ? <Text style={{ color: colors.error }}>{error}</Text> : null}{busy ? <ActivityIndicator /> : null}
      {isCoach ? payload?.programs.map((program) => <ProgramCard key={program.id} program={program} enrollments={payload.enrollments.filter((item) => item.program_id === program.id)} colors={colors} players={players} onEdit={() => openBuilder(program)} onPublish={() => confirmPublish(program)} onEnroll={() => openEnrollment(program)} onArchive={() => confirmArchive(program)} onEnrollmentStatus={changeEnrollment} />) : mine.map((enrollment) => <PlayerProgramCard key={enrollment.id} enrollment={enrollment} colors={colors} />)}
      {(isCoach ? !payload?.programs.length : !mine.length) ? <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.text }]}>No programs yet</Text><Text style={{ color: colors.textSecondary }}>{isCoach ? 'Create a guided draft to get started.' : 'Your coach has not enrolled you in a program.'}</Text></View> : null}
    </ScrollView>
    <BuilderModal visible={builderOpen} step={builderStep} setStep={setBuilderStep} draft={draft} templates={templates} colors={colors} validation={validation} busy={busy} onClose={() => setBuilderOpen(false)} updateDraft={updateDraft} addPhase={addPhase} updatePhase={updatePhase} removePhase={removePhase} addTemplate={addTemplate} addCustomItem={addCustomItem} updateItem={updateItem} removeItem={removeItem} save={saveDraft} />
    <EnrollmentModal program={enrollProgram} players={players} teams={teams} selectedPlayers={selectedPlayers} selectedTeam={selectedTeam} startDate={startDate} colors={colors} busy={busy} setPlayers={setSelectedPlayers} setTeam={setSelectedTeam} setStartDate={setStartDate} close={() => setEnrollProgram(null)} submit={submitEnrollment} />
  </>;
}

function ProgramCard({ program, enrollments, colors, players, onEdit, onPublish, onEnroll, onArchive, onEnrollmentStatus }: any) { const playerName = (id: string) => players.find((player: OwnerPlayerCrmPlayer) => player.playerId === id)?.displayName ?? 'Player'; const confirmStatus = (id: string, status: ProgramEnrollmentStatus) => { if (status === 'active' || status === 'paused') { void onEnrollmentStatus(id, status); return; } Alert.alert(`${status === 'completed' ? 'Complete' : 'Cancel'} enrollment?`, 'The player history is preserved.', [{ text: 'Back', style: 'cancel' }, { text: status === 'completed' ? 'Complete' : 'Cancel enrollment', style: status === 'cancelled' ? 'destructive' : 'default', onPress: () => void onEnrollmentStatus(id, status) }]); }; return <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.row}><Text style={[styles.cardTitle, styles.grow, { color: colors.text }]}>{program.title}</Text><Pill label={program.status} active={program.status === 'published'} /></View><Text style={{ color: colors.textSecondary }}>{program.duration_weeks} weeks · {program.phases.length} phases · {program.items.length} items</Text>{program.description ? <Text style={{ color: colors.text }}>{program.description}</Text> : null}<View style={styles.actionRow}>{program.status === 'draft' ? <><Action label="Edit" onPress={onEdit} /><Action label="Publish" onPress={onPublish} /></> : null}{program.status === 'published' ? <><Action label="Enroll" onPress={onEnroll} /><Action label="Archive" onPress={onArchive} danger /></> : null}</View>{enrollments.map((enrollment: any) => <View key={enrollment.id} style={[styles.enrollment, { borderColor: colors.border }]}><View style={styles.row}><Text style={{ color: colors.text, fontWeight: '700' }}>{playerName(enrollment.player_id)}</Text><Pill label={enrollment.status} active={enrollment.status === 'active'} /></View><Text style={{ color: colors.textSecondary }}>Starts {enrollment.start_date}</Text><View style={styles.actionRow}>{enrollment.status === 'active' ? <Action label="Pause" onPress={() => confirmStatus(enrollment.id, 'paused')} /> : null}{enrollment.status === 'paused' ? <Action label="Resume" onPress={() => confirmStatus(enrollment.id, 'active')} /> : null}{!['completed', 'cancelled'].includes(enrollment.status) ? <><Action label="Complete" onPress={() => confirmStatus(enrollment.id, 'completed')} /><Action label="Cancel" danger onPress={() => confirmStatus(enrollment.id, 'cancelled')} /></> : null}</View></View>)}</View>; }
function PlayerProgramCard({ enrollment, colors }: any) { const completed = enrollment.program_enrollment_items.filter((item: any) => item.status === 'completed').length; const total = enrollment.program_enrollment_items.length; return <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.row}><Text style={[styles.cardTitle, styles.grow, { color: colors.text }]}>{enrollment.training_programs.title}</Text><Pill label={enrollment.status} active={enrollment.status === 'active'} /></View><Text style={{ color: colors.textSecondary }}>Started {enrollment.start_date} · {enrollment.training_programs.duration_weeks} weeks</Text><Text style={{ color: colors.text, fontWeight: '700' }}>{completed}/{total} completed</Text>{enrollment.program_enrollment_items.map((item: any) => <View key={item.id} style={[styles.item, { borderColor: colors.border }]}><View style={styles.grow}><Text style={{ color: colors.text, fontWeight: '600' }}>{item.title}</Text><Text style={{ color: colors.textSecondary }}>{item.item_type.replaceAll('_', ' ')}</Text></View><Text style={{ color: colors.textSecondary }}>{item.scheduled_date}</Text></View>)}</View>; }

function BuilderModal(props: any) { const { visible, step, setStep, draft, templates, colors, validation, busy, onClose, updateDraft, addPhase, updatePhase, removePhase, addTemplate, addCustomItem, updateItem, removeItem, save } = props; const stepNames = ['Details', 'Phases', 'Content', 'Preview']; return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={styles.modalContent} keyboardShouldPersistTaps="handled"><View style={styles.row}><TouchableOpacity onPress={onClose}><Text style={{ color: colors.primary, fontWeight: '700' }}>Cancel</Text></TouchableOpacity><Text style={[styles.cardTitle, { color: colors.text }]}>{draft.programId ? 'Edit program' : 'New program'}</Text><Text style={{ color: colors.textSecondary }}>{step}/4</Text></View><View style={styles.steps}>{stepNames.map((name, index) => <TouchableOpacity key={name} onPress={() => setStep((index + 1) as BuilderStep)} style={[styles.step, step === index + 1 && styles.stepActive]}><Text style={{ color: step === index + 1 ? '#fff' : colors.textSecondary, fontSize: 12 }}>{name}</Text></TouchableOpacity>)}</View>
    {step === 1 ? <View style={styles.section}><Field label="Title" value={draft.title} setValue={(title: string) => updateDraft({ title })} colors={colors} /><Field label="Description" value={draft.description} setValue={(description: string) => updateDraft({ description })} colors={colors} multiline /><Field label="Audience" value={draft.audience} setValue={(audience: string) => updateDraft({ audience })} colors={colors} placeholder="e.g. U15 strikers" /><View style={styles.field}><Text style={[styles.label, { color: colors.textSecondary }]}>Level</Text><View style={styles.chips}>{PROGRAM_LEVELS.map((level) => <Chip key={level.value} label={level.label} selected={draft.level === level.value} onPress={() => updateDraft({ level: level.value })} colors={colors} testID={`programs.level.${level.value}`} />)}</View></View><Field label="Duration in weeks" value={draft.durationWeeks} setValue={(durationWeeks: string) => updateDraft({ durationWeeks })} colors={colors} keyboardType="number-pad" /></View> : null}
    {step === 2 ? <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.text }]}>Phases and weeks</Text><Text style={{ color: colors.textSecondary }}>{draft.durationWeeks}-week program · new phases start after the previous phase by default</Text>{draft.phases.map((phase: PhaseDraft) => { const startWeek = Number(phase.weekOffset) + 1; const endWeek = startWeek + Number(phase.durationWeeks) - 1; return <View key={phase.id} style={[styles.subcard, { borderColor: colors.border }]}><Field label="Phase name" value={phase.title} setValue={(title: string) => updatePhase(phase.id, { title })} colors={colors} /><View style={styles.row}><View style={styles.grow}><Field label="Starts in week" value={String(startWeek)} setValue={(value: string) => updatePhase(phase.id, { weekOffset: String(Math.max(0, Number(value) - 1)) })} colors={colors} keyboardType="number-pad" /></View><View style={styles.grow}><Field label="Duration (weeks)" value={phase.durationWeeks} setValue={(durationWeeks: string) => updatePhase(phase.id, { durationWeeks })} colors={colors} keyboardType="number-pad" /></View></View><Text style={{ color: endWeek > Number(draft.durationWeeks) ? colors.error : colors.textSecondary }}>{startWeek === endWeek ? `Runs in week ${startWeek}` : `Runs from week ${startWeek} to week ${endWeek}`}</Text><Action label="Remove phase" danger onPress={() => removePhase(phase.id)} /></View>; })}<TouchableOpacity style={styles.secondaryButton} onPress={addPhase}><Text style={{ color: colors.primary, fontWeight: '700' }}>+ Add phase</Text></TouchableOpacity></View> : null}
    {step === 3 ? <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.text }]}>Program content</Text>{draft.items.map((item: ItemDraft) => <View key={item.id} style={[styles.subcard, { borderColor: colors.border }]}><Field label="Title" value={item.title} setValue={(title: string) => updateItem(item.id, { title })} colors={colors} /><Text style={{ color: colors.textSecondary }}>{item.itemType.replaceAll('_', ' ')}</Text><Text style={{ color: colors.textSecondary }}>Phase</Text><View style={styles.chips}>{draft.phases.map((phase: PhaseDraft) => <Chip key={phase.id} label={phase.title} selected={item.phaseId === phase.id} onPress={() => updateItem(item.id, { phaseId: phase.id })} colors={colors} />)}</View><Field label="Day from program start (0 = first day)" value={item.dayOffset} setValue={(dayOffset: string) => updateItem(item.id, { dayOffset })} colors={colors} keyboardType="number-pad" /><Action label="Remove item" danger onPress={() => removeItem(item.id)} /></View>)}<Text style={[styles.label, { color: colors.text }]}>Add saved template</Text><View style={styles.chips}>{templates.map((template: TrainingTemplateSummary) => <Chip key={template.id} label={`${template.title} · ${template.templateType}`} selected={false} onPress={() => addTemplate(template)} colors={colors} />)}</View><TouchableOpacity style={styles.secondaryButton} onPress={addCustomItem}><Text style={{ color: colors.primary, fontWeight: '700' }}>+ Add focus item</Text></TouchableOpacity></View> : null}
    {step === 4 ? <View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.text }]}>Review program</Text><Text style={[styles.cardTitle, { color: colors.text }]}>{draft.title || 'Untitled'}</Text><Text style={{ color: colors.textSecondary }}>{draft.durationWeeks} weeks · {draft.phases.length} phases · {draft.items.length} items</Text>{draft.phases.map((phase: PhaseDraft) => <View key={phase.id} style={[styles.subcard, { borderColor: colors.border }]}><Text style={{ color: colors.text, fontWeight: '700' }}>{phase.title}</Text><Text style={{ color: colors.textSecondary }}>Week {Number(phase.weekOffset) + 1} · {phase.durationWeeks} week(s)</Text>{draft.items.filter((item: ItemDraft) => item.phaseId === phase.id).sort((a: ItemDraft, b: ItemDraft) => Number(a.dayOffset) - Number(b.dayOffset)).map((item: ItemDraft) => <Text key={item.id} style={{ color: colors.text }}>Day {Number(item.dayOffset) + 1}: {item.title}</Text>)}</View>)}{validation ? <Text style={{ color: colors.error }}>{validation}</Text> : <Text style={{ color: '#16a34a', fontWeight: '700' }}>Ready to save as draft</Text>}</View> : null}
    <View style={styles.footer}>{step > 1 ? <TouchableOpacity style={styles.secondaryButton} onPress={() => setStep((step - 1) as BuilderStep)}><Text style={{ color: colors.primary, fontWeight: '700' }}>Back</Text></TouchableOpacity> : <View />}{step < 4 ? <TouchableOpacity style={styles.primaryCompact} onPress={() => setStep((step + 1) as BuilderStep)}><Text style={styles.primaryText}>Next</Text></TouchableOpacity> : <TouchableOpacity disabled={busy || Boolean(validation)} style={[styles.primaryCompact, Boolean(validation) && styles.disabled]} onPress={() => void save()}><Text style={styles.primaryText}>{busy ? 'Saving…' : 'Save draft'}</Text></TouchableOpacity>}</View></ScrollView></Modal>; }

function EnrollmentModal({ program, players, teams, selectedPlayers, selectedTeam, startDate, colors, busy, setPlayers, setTeam, setStartDate, close, submit }: any) { if (!program) return null; const toggle = (id: string) => setPlayers(selectedPlayers.includes(id) ? selectedPlayers.filter((value: string) => value !== id) : [...selectedPlayers, id]); const selectedTeamData = teams.find((team: OwnerPlayerCrmTeam) => team.id === selectedTeam); const previewPlayers = selectedTeam ? selectedTeamData?.memberCount ?? 0 : selectedPlayers.length; return <Modal visible animationType="slide" onRequestClose={close}><ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={styles.modalContent}><View style={styles.row}><TouchableOpacity onPress={close}><Text style={{ color: colors.primary, fontWeight: '700' }}>Cancel</Text></TouchableOpacity><Text style={[styles.cardTitle, { color: colors.text }]}>Enroll in {program.title}</Text><View /></View><Field label="Start date (YYYY-MM-DD)" value={startDate} setValue={setStartDate} colors={colors} /><Text style={[styles.sectionTitle, { color: colors.text }]}>Players</Text><View style={styles.chips}>{players.map((player: OwnerPlayerCrmPlayer) => <Chip key={player.playerId} label={player.displayName} selected={!selectedTeam && selectedPlayers.includes(player.playerId)} onPress={() => { setTeam(null); toggle(player.playerId); }} colors={colors} />)}</View>{teams.length ? <><Text style={[styles.sectionTitle, { color: colors.text }]}>Or enroll a team</Text><View style={styles.chips}>{teams.map((team: OwnerPlayerCrmTeam) => <Chip key={team.id} label={`${team.name} (${team.memberCount ?? 0})`} selected={selectedTeam === team.id} onPress={() => { setPlayers([]); setTeam(selectedTeam === team.id ? null : team.id); }} colors={colors} />)}</View></> : null}<View style={[styles.card, { borderColor: colors.border, backgroundColor: colors.card }]}><Text style={[styles.cardTitle, { color: colors.text }]}>Enrollment preview</Text><Text style={{ color: colors.text }}>{previewPlayers} player(s) · starts {startDate}</Text>{program.items.slice().sort((a: any, b: any) => a.day_offset - b.day_offset).map((item: any) => <Text key={item.id} style={{ color: colors.textSecondary }}>{addDays(startDate, item.day_offset)} · {item.title}</Text>)}</View><TouchableOpacity disabled={busy || !previewPlayers || !/^\d{4}-\d{2}-\d{2}$/.test(startDate)} style={[styles.primary, (!previewPlayers || busy) && styles.disabled]} onPress={() => void submit()}><Text style={styles.primaryText}>{busy ? 'Enrolling…' : 'Confirm enrollment'}</Text></TouchableOpacity></ScrollView></Modal>; }
function Field({ label, value, setValue, colors, ...rest }: any) { return <View style={styles.field}><Text style={[styles.label, { color: colors.textSecondary }]}>{label}</Text><TextInput value={value} onChangeText={setValue} placeholderTextColor={colors.textSecondary} style={[styles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.card }]} {...rest} /></View>; }
function Chip({ label, selected, onPress, colors, testID }: any) { return <TouchableOpacity testID={testID} accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={[styles.chip, { borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? colors.primary : colors.card }]}><Text style={{ color: selected ? '#fff' : colors.text, fontWeight: '600' }}>{label}</Text></TouchableOpacity>; }
function Pill({ label, active }: { label: string; active: boolean }) { return <View style={[styles.pill, { backgroundColor: active ? '#dcfce7' : '#e2e8f0' }]}><Text style={{ color: active ? '#166534' : '#475569', fontWeight: '700', textTransform: 'capitalize' }}>{label}</Text></View>; }
function Action({ label, onPress, danger }: { label: string; onPress: () => void; danger?: boolean }) { return <TouchableOpacity onPress={onPress} style={styles.action}><Text style={{ color: danger ? '#dc2626' : '#2563eb', fontWeight: '700' }}>{label}</Text></TouchableOpacity>; }

const styles = StyleSheet.create({ center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, grow: { flex: 1 }, content: { padding: 16, paddingBottom: 120, gap: 14 }, modalContent: { padding: 20, paddingTop: 60, paddingBottom: 60, gap: 18 }, heading: { fontSize: 28, fontWeight: '800' }, sectionTitle: { fontSize: 18, fontWeight: '800' }, section: { gap: 14 }, card: { borderWidth: 1, borderRadius: 16, padding: 16, gap: 10 }, subcard: { borderWidth: 1, borderRadius: 12, padding: 12, gap: 10 }, cardTitle: { fontSize: 17, fontWeight: '800' }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 }, action: { paddingVertical: 5 }, enrollment: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 10, gap: 7 }, field: { gap: 5 }, label: { fontSize: 13, fontWeight: '600' }, input: { borderWidth: 1, borderRadius: 10, padding: 12, minHeight: 46 }, primary: { backgroundColor: '#2563eb', padding: 14, borderRadius: 10, alignItems: 'center' }, primaryCompact: { backgroundColor: '#2563eb', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 10 }, primaryText: { color: '#fff', fontWeight: '800' }, secondaryButton: { padding: 11, borderRadius: 10, alignItems: 'center' }, disabled: { opacity: 0.45 }, item: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderRadius: 20, paddingVertical: 8, paddingHorizontal: 12 }, pill: { borderRadius: 12, paddingVertical: 4, paddingHorizontal: 9 }, steps: { flexDirection: 'row', gap: 5 }, step: { flex: 1, backgroundColor: '#e2e8f0', padding: 7, borderRadius: 8, alignItems: 'center' }, stepActive: { backgroundColor: '#2563eb' }, footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 } });
